name: Build and Deploy KiraBot Server to GCP VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for building the image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kirabot-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Set up SSH key for GCP VM
      - name: Set up SSH key
        run: |
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key

      # Deploy to GCP VM via SSH
      - name: Deploy to GCP VM
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key chakitsharma444@${{ secrets.GCP_VM_IP }} << 'EOF'
            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/kirabot-server:latest
            
            # Stop and remove existing container (if any)
            docker stop kirabot-server || true
            docker rm kirabot-server || true
            
            # Run the new container
            docker run -d -p 8000:8000 --name kirabot-server \
              --env-file /home/chakitsharma444/KiraBot/.env \
              ${{ secrets.DOCKERHUB_USERNAME }}/kirabot-server:latest
            
            # Clean up unused images
            docker image prune -f
          EOF
        env:
          GCP_SSH_PRIVATE_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          GCP_VM_IP: ${{ secrets.GCP_VM_IP }}